In [1]:
pip install fitz

Requirement already satisfied: fitz in c:\users\user\anaconda3\lib\site-packages (0.0.1.dev2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: configobj in c:\users\user\anaconda3\lib\site-packages (from fitz) (5.0.9)
Requirement already satisfied: configparser in c:\users\user\anaconda3\lib\site-packages (from fitz) (7.2.0)
Requirement already satisfied: httplib2 in c:\users\user\anaconda3\lib\site-packages (from fitz) (0.31.2)
Requirement already satisfied: nibabel in c:\users\user\anaconda3\lib\site-packages (from fitz) (5.4.2)
Requirement already satisfied: nipype in c:\users\user\anaconda3\lib\site-packages (from fitz) (1.11.0)
Requirement already satisfied: numpy in c:\users\user\anaconda3\lib\site-packages (from fitz) (2.1.3)
Requirement already satisfied: pandas in c:\users\user\anaconda3\lib\site-packages (from fitz) (2.2.3)
Requirement already satisfied: pyxnat in c:\users\user\anaconda3\lib\site-packages (from fitz) (1.6.4)
Requirement already satisfied: scipy in c:\users\user\anaconda3\lib\site-packages (from fitz) (1.15.3)
Requirement already satisfied: pyparsing<4,>=3.1 in c:\users\user\anaconda3\lib\site-packages (from httplib2->fitz) (3.2.0)
Requirement already satisfied: packaging>=20 in c:\users\user\anaconda3\lib\site-packages (from nibabel->fitz) (24.2)
Requirement already satisfied: acres>=0.3.0 in c:\users\user\anaconda3\lib\site-packages (from nipype->fitz) (0.5.0)
Requirement already satisfied: click>=6.6.0 in c:\users\user\anaconda3\lib\site-packages (from nipype->fitz) (8.1.8)
Requirement already satisfied: etelemetry>=0.3.1 in c:\users\user\anaconda3\lib\site-packages (from nipype->fitz) (0.3.1)
Requirement already satisfied: filelock>=3.0.0 in c:\users\user\anaconda3\lib\site-packages (from nipype->fitz) (3.17.0)
Requirement already satisfied: looseversion!=1.2,>=1.0.1 in c:\users\user\anaconda3\lib\site-packages (from nipype->fitz) (1.3.0)
Requirement already satisfied: lxml>=4.9.1 in c:\users\user\anaconda3\lib\site-packages (from nipype->fitz) (5.3.0)
Requirement already satisfied: networkx>=2.5 in c:\users\user\anaconda3\lib\site-packages (from nipype->fitz) (3.4.2)
Requirement already satisfied: prov>=1.5.2 in c:\users\user\anaconda3\lib\site-packages (from nipype->fitz) (2.1.1)
Requirement already satisfied: puremagic>=1.15 in c:\users\user\anaconda3\lib\site-packages (from nipype->fitz) (2.1.0)
Requirement already satisfied: pydot>=1.2.3 in c:\users\user\anaconda3\lib\site-packages (from nipype->fitz) (4.0.1)
Requirement already satisfied: python-dateutil>=2.2 in c:\users\user\anaconda3\lib\site-packages (from nipype->fitz) (2.9.0.post0)
Requirement already satisfied: rdflib>=5.0.0 in c:\users\user\anaconda3\lib\site-packages (from nipype->fitz) (7.6.0)
Requirement already satisfied: simplejson>=3.8.0 in c:\users\user\anaconda3\lib\site-packages (from nipype->fitz) (3.20.2)
Requirement already satisfied: traits>=6.2 in c:\users\user\anaconda3\lib\site-packages (from nipype->fitz) (7.1.0)
Requirement already satisfied: colorama in c:\users\user\anaconda3\lib\site-packages (from click>=6.6.0->nipype->fitz) (0.4.6)
Requirement already satisfied: requests in c:\users\user\anaconda3\lib\site-packages (from etelemetry>=0.3.1->nipype->fitz) (2.32.3)
Requirement already satisfied: ci-info>=0.2 in c:\users\user\anaconda3\lib\site-packages (from etelemetry>=0.3.1->nipype->fitz) (0.4.0)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.2->nipype->fitz) (1.17.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\lib\site-packages (from pandas->fitz) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\anaconda3\lib\site-packages (from pandas->fitz) (2025.2)
Requirement already satisfied: pathlib>=1.0 in c:\users\user\anaconda3\lib\site-packages (from pyxnat->fitz) (1.0.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\anaconda3\lib\site-packages (from requests->etelemetry>=0.3.1->nipype->fitz) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\anaconda3\lib\site-packages (from requests->etelemetry>=0.3.1->nipype->fitz) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\anaconda3\lib\site-packages (from requests->etelemetry>=0.3.1->nipype->fitz) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\anaconda3\lib\site-packages (from requests->etelemetry>=0.3.1->nipype->fitz) (2026.2.25)

In [2]:
pip install PyMuPDF

Requirement already satisfied: PyMuPDF in c:\users\user\anaconda3\lib\site-packages (1.27.2)Note: you may need to restart the kernel to use updated packages.

In [3]:
import fitz
import pandas as pd
import io
import glob

In [40]:
# загрузка в list пути всех нужных pdf файлов
all_pdf = glob.glob(r"PDF-Copy1\*.pdf")

In [41]:
len(all_pdf)

18

In [42]:
all_pdf

['PDF-Copy1\\AI-диджей Spotify иногда не понимает даже простые музыкальные запросы _ Хабр.pdf',
 'PDF-Copy1\\Docker_Podman-клиент и Remote-клиент для GigaIDE _ Хабр.pdf',
 'PDF-Copy1\\Meta может сократить до 20% сотрудников на фоне роста расходов на AI _ Хабр.pdf',
 'PDF-Copy1\\Автоматизируем сканирование инфраструктуры_ скрипт 3.0 для Сканер-ВС 7 _ Хабр.pdf',
 'PDF-Copy1\\Генерация изображений в Nano Banana_ Промпты и гайд по использованию Gemini 3 Pro_Flash _ Хабр.pdf',
 'PDF-Copy1\\Делимся опытом защиты и мониторинга безопасности медиахолдинга _ Хабр.pdf',
 'PDF-Copy1\\Изучаем 5GBE-сети _ Хабр.pdf',
 'PDF-Copy1\\Как недорогой MacBook Neo за $600 меняет рынок ноутбуков на Windows _ Хабр.pdf',
 'PDF-Copy1\\Как расти QA-инженеру_ инструменты, которые действительно работают _ Хабр.pdf',
 'PDF-Copy1\\Как создатель первой веб-камеры был вынужден продать все свои разработки_ история Connectix _ Хабр.pdf',
 'PDF-Copy1\\Как я делал эконом-вариант датчика качества воздуха для своего Home Assistant и что из этого вышло _ Хабр.pdf',
 'PDF-Copy1\\Как\xa0Нейроюрист ищет по\xa0миллионам юридических документов с\xa0помощью векторного поиска YDB _ Хабр.pdf',
 'PDF-Copy1\\Кибербезопасность финансовой отрасли России в 2026 году_ тенденции защиты и атак _ Хабр.pdf',
 'PDF-Copy1\\Космос-2055_ как будет выглядеть космонавтика через 30 лет_ _ Хабр.pdf',
 'PDF-Copy1\\Поделить огромный проект с автотестами на 50 команд, чтобы QA был счастлив _ Хабр.pdf',
 'PDF-Copy1\\Принципы организационного проектирования _ Хабр.pdf',
 'PDF-Copy1\\Хлеб на закваске как управляемый процесс _ Хабр.pdf',
 'PDF-Copy1\\Что случилось с CGI, и как FastCGI спас веб от катастрофы_ _ Хабр.pdf']

In [43]:
pdf_document = r"PDF-Copy1\\Изучаем 5GBE-сети _ Хабр.pdf"
doc = fitz.open(pdf_document)
print("Исходный документ: ", doc)
print("\nКоличество страниц: %i\n\n------------------\n\n" % doc.page_count)
print(doc.metadata)
for current_page in range(len(doc)):
    page = doc.load_page(current_page)
    page_text = page.get_text("text")
    print("Стр. ", current_page+1, "\n")
    print(page_text)

Исходный документ:  Document('PDF-Copy1\\Изучаем 5GBE-сети _ Хабр.pdf')

Количество страниц: 25

------------------


{'format': 'PDF 1.4', 'title': 'Изучаем 5GBE-сети / Хабр', 'author': '', 'subject': '', 'keywords': '', 'creator': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36', 'producer': 'Skia/PDF m145', 'creationDate': "D:20260315145947+00'00'", 'modDate': "D:20260315145947+00'00'", 'trapped': '', 'encryption': None}
Стр.  1

3031.1
Общий рейтинг
RUVDS.com
VDS/VPS-хостинг. Скидка 15% по коду HABR15
Подписаться
Какое железо есть на рынке
Стандарт 5 Гбит очень новый, ему буквально несколько лет, поэтому чипов, которые его
поддерживают, совсем немного, но они всё же есть.
Если говорить про нативную PCIE карту, которая поддерживает максимум 5GbE, то есть аж 2
варианта:
Marvell AQtion AQC111C.
Realtek RTL8126.
Marvell AQC111C
Решение от Marvell AQC111C интересно тем, что иногда выпускается в конфигурации аж на 4
порта, есть также карты и на 1 порт. Судя по тестам в сети, уровень потребления и нагрева
немного выше, чем у решения от Realtek. К сожалению, для РФ этот вариант можно сразу
вычёркивать, так как купить его на маркетплейсах просто невозможно, а за рубежом цены
сильно выше, чем у конкурента.
Tirarex 1 час назад
Изучаем 5GBE-сети
Простой
7 мин
2.3K
Блог компании RUVDS.com, Сетевое оборудование, Сетевые технологии*, Серверное администрирование*
Обзор
Все потоки
Узнали, сколько получают в IT
Войти

Стр.  2

Сюда же впишу QC111U, это тот же чип от «Марвел», но уже с USB интерфейсом. На его основе
уже выпущены USB донглы, даже у вполне именитых в узких кругах фирм, таких как, например,
StarTech и TRENDnet. Но в целом ситуация схожа с PCIE решением от этой же фирмы. Чип
дороже, немного горячее, и в РФ его не купить. На ServeTheHome даже есть обзор нескольких
таких донглов.
(источник https://au.world.taobao.com/item/RHhGTjFhc3FobkhRZ2Flejc1TGh2UT09.htm)
Realtek RTL8126
Решение Realtek RTL8126 уже намного интереснее, банально благодаря широкому
распространению на маркетплейсах РФ и ужасно низкой цене (примерно 850–100 рублей за
сетевую карту на один порт). Чип не горячий, поэтому при наличии небольшого радиатора можно
сказать, что обдува он не требует.

Стр.  3

(источник — магазин OZON)
При этом он получил какую-то неслыханную любовь в Китае, без каких-либо проблем можно
найти сетевые карты в m.2 формате с ключами A+E и B+M и т. д.
Таким образом можно заменить Wi-Fi модуль на проводную сеть 5 Гбит или поставить сетевую
карту в свободный слот для обычных SSD дисков формата 2280. Это, как по мне, очень крутой
бонус для маленьких ПК и даже ноутбуков.

Стр.  4

Отдельно хочется отметить интерфейс подключения, ведь это PCIE 3-й версии и всего 1 линия!
Таким образом, эти карты можно ставить в тот самый X1 слот, который обычно стоит без дела.
Realtek RTL8157
Владельцев ноутбуков тоже не обделили. У «Риалтека» есть чип RTL8157, который
поддерживает 5GbE сеть через USB соединение. Для работы требуется абсолютно обычный, я
бы сказал, уже старый и добрый USB 3 порт на скорости 5 Гбит/сек.
Естественно, скорость будет немного ниже, а пинг выше из-за задержек USB стека, но в целом
это, наверное, самое оптимальное решение для получения высоких скоростей на ноутбуке без
какого-либо вмешательства в его железо.
При этом всём стоимость этого решения очень демократичная:

Стр.  5

А их уже куда-то ставят?
На удивление, да! Несмотря на новизну стандарта, в том же DNS можно найти много плат с
поддержкой сети 5GbE. Буквально все они используют чип RTL8126, так как он банально без
особых доработок встаёт на место RTL8125. Конечно, большинство этих плат из среднего-
высокого ценового сегмента, но, если смотреть на цену самого чипа, вопрос его появления в
бюджетных платах — лишь вопрос времени.
(источник — магазин DNS)
Свичи
Их, можно сказать, что нет, и это на данный момент самая большая проблема.

Стр.  6

В середине 2025 года на Computex был показан свич SR-S5G3008, но на практике найти его в
продаже мне пока не удалось.
Также недавно на рынке появился NICGIGA S50-0800 за 169 $, и на него есть обзор на
ServeTheHome.
Но, смотря на строение свича, я бы провёл аналогию с 2.5GbE свичами на момент их
зарождения. Это Gen1 свич, где каждый порт использует отдельную микросхему, а объединяет
их RTL9303, решение на 10 Гбит, которое тут работает в полсилы.
В отличии от Gen2 решений, где весь свич использует одну микросхему, эта компоновка требует
больше питания, и, соответственно, греется сильнее.

Стр.  7

(Пример GEn2 свича стандарта 2.5GbE, источник https://www.acwifi.net/24353.html)
Если провести аналогию со свичами на стандарте 2,5GbE, то мы сейчас где-то в паре лет от
появления дешёвых и энергоэффективных 5GbE свичей.
Обратная совместимость
С обратной совместимостью всё неплохо, но только если у вас свежее 10GbE железо. Старые
контроллеры, изготовленные до стандарта 802.3bz (примерно все до 2016 года), банально не
заработают на стандарте 5GbE и 2.5GbE.
Например, такие контроллеры, как:
Intel X540.
Intel X550 старых ревизий.
Intel 82599 не смогут согласовать 5 Гбит и будут работать на скорости 1 Гбит/сек.
Но более свежие контроллеры типа X710 или нового RTL8127 без проблем смогут работать на
стандарте 5 Гбит.
С 10G SFP+ на ETH адаптерами ситуация идентичная, нужно искать более свежие адаптеры, на
которых указано, что есть поддержка 5 Гбит линка. Но на практике, если указано, что работает
стандарт 2,5 Гбит, то с шансом 99 % будет работать и 5 Гбит.

Стр.  8

Что купил я
На синем маркетплейсе было взято 2 сетевых карты без бренда, по цене 1000руб/шт. Ради
интереса я брал самые простые карты без радиаторов охлаждения, дабы понять, как это всё
будет греться.
На практике мне пришли карты с брендированием IOCREST. В комплекте была инструкция и 2
планки разных размеров.

Стр.  9

Чего-то особого про карту сказать не получится. На плате чип Realtek RTL8126, пара
преобразователей питания, чип памяти с прошивкой и трансформатор с сетевым портом. Планку
можно поменять на низкопрофильную (2U), но на практике, если планку снять, то карта влезает
в 1U сервер вертикально.
Забегая вперёд, скажу, что стоит брать карту с охлаждением, так как при работе на
максимальных скоростях эта карта перегревается и троттлит.

Стр.  10


Стр.  11


Стр.  12

Запуск в Proxmox
После установки карты и запуска сервера Proxmox не имел сеть. Как обычно, ID адаптера
сменился с enpXs0 на enpX+1s0, ведь мы поставили новое устройство. После правки файла с
настройками сетевых интерфейсов я так и не увидел новый сетевой порт.
Дело в том, что чип Realtek 8126 очень новый, и драйвер под него появился только в ядре 6.14, а
моя система работает на ядре 6.13. Удачно совпало, что на момент экспериментов вышел
Proxmox 9 с ядром 6.14, и можно совместить неприятное с болезненным и обновить как сам
Proxmox, так и ядро.
Процесс обновления подробно описывать не стану, действовал по инструкции
https://pve.proxmox.com/wiki/Upgrade_from_8_to_9, обновление было сломано пакетом
докера, который я ставил очень давно, и это вообще неправда. apt fix broken install решил
удалить proxmox ve пакеты, в общем, ситуация схожая с той самой «steam install remove my
de». Ремонтировать это всё не стал, ведь Proxmox — это не про жёсткую привязку к текущей
установке. Забекапил все виртуальные машины, переустановил систему из свежего ISO
образа с официального сайта и развернул бекап обратно. Благо 10 Гбит сеть тут не просто
так, и на всё ушло меньше часа.

Стр.  13

В остальном на свежем Proxmox 9 версии никаких проблем нет. Устройство видится с
нормальным названием (если у вас нет приписки про 5GbE контроллер, то драйвера нет).
Порт 5GbE карты закинул в бридж, воткнул в него кабель до свича, Proxmox сразу получил свой
IP и веб морда работает без проблем.
Подключаем кабель, вызываем ethtool eth0  и видим, что адаптер поддерживает и все
стандарты до 5 Гбит включительно, а также без проблем заработал на скорости 5 Гбит.

Стр.  14

В целом, если у вас на сервере стоит «Линукс» со свежим ядром, то установка карты буквально
PlugNPlay.
Запуск в Windows
Сразу после запуска системы (Windows 11 24H2 - 26100.4946) сеть заработала без установки
каких-либо дополнительных драйверов и без ручных настроек. IP получен, линк 5 Гбит, и
Windows это прекрасно видит.

Стр.  15

Запуск в TrueNAS
Всё не так однозначно. В версии Fangtooth (25.4) и выше драйвер уже есть из коробки, карта
после установки видна и без проблем работает.
Для более старых версий понадобится произвести процесс танца с бубном по установке
драйвера, который описан тут.
Тесты — в браузере — неудачные
Первым делом я решил прогнать обычный speed test между моим основным ПК (Windows 11
24h2) и Proxmox сервером (порт 5GbE в бридже с основным портом 2.5GbE, Proxmox 9, speed
test живёт в докере, докер в виртуалке «Убунты» с 4 ядрами и 8 ГБ оперативной памяти).
Результат из коробки на стоковых настройках можно лицезреть ниже. До 5 Гбит не дотягивает, но
уже выше, чем младший стандарт в 2,5 Гбит.

Стр.  16

Пробуем поднять скорость методом настройки.
В Windows меняю MTU на 9000. Сделать это можно в настройках устройства в диспетчере
устройств. Пункт называется «большой кадр», и выставить его надо на 9014 байт.
В Proxmox делаем то же самое со всеми интерфейсами, а потом с бриджем.

Стр.  17

И после теста получаем результат даже хуже, чем было раньше...
Тесты — в браузере — удачные
Я провёл много тестов, менял провода, менял MTU, настройки виртуальной машины и даже
гонял тесты на Baremetal, а не виртуалке, но в итоге проблема была в Firefox, банально тест
скорости в «Огнелисе» показывает меньшие результаты, чем в хроме.

Стр.  18

Тесты — Iperf3
Обычный тест (iperf3 -c ipсервера -t 60 -P 16) показал 4,75 Гбит/сек, но результат был
нестабилен и падал вплоть до 1,4 Гбит.
Проблема была простая — перегрев сетевой карты. К сожалению, китайцы пожалели даже
крошечный радиатор, и плата на полной скорости может работать около 2 минут, после чего
начинает троттлить.
Нагрев через тепловизор выглядит так. Видно, что греется сам чип Realtek и один из
преобразователей питания. Троттлинг начинается при достижении 60 градусов на чипе.
Небольшой обдув за счёт корпусного вентилятора полностью решает проблему перегрева, но в
будущем я бы брал карту с радиатором.

Стр.  19

Но стоит дать даже минимальный обдув (закрыл крышку сервера, и вентиляторы начали
минимально обдувать карту) — и скорость сразу стабилизируется на 4,75 Гбит без просадок.

Стр.  20

Тот же тест, но в обратную сторону показал идентичную скорость в 4,74 Гбит/сек. Тут значение
MTU стоит на стандартных 1500, так как если ставить 9000, скорость упадёт до 3,4 Гбит/сек.

Стр.  21

Тесты — Реальные скорости
Тесты выше показывали, как работает сама сеть, но какие же реальные цифры будут при записи
файлов по такой сети?
Для этого я расшарил папку на виртуалке с Windows (стоит на GEN4 X4 SSD диске «Самсунг») и
провёл тесты CrystalDiskInfo.
Результаты мне нравятся. При хорошем NVMe диске на сервере можно добиться результатов
уровня SATA SSD дисков. Мелкоблочные результаты, конечно, не впечатляют, это можно
отстроить, сделав NAS отдельной железкой и тонко подстроив параметры, но это уже тема для
отдельной статьи.

Стр.  22

Копирование тестового файла в 40 ГБ не вызывает никаких вопросов. Скорость колеблется в
районе 560–570 мегабайт в секунду, что конвертируется в 4,8–4,9 Гбит/сек.

Стр.  23


Стр.  24

Потребление
Для тестов потребления я подключил карту с RTL8126 через PCIE X1 рейзер, а рейзер запитал
через тестер KM003C. На рейзере 2 преобразователя напряжений для 5 и 3,3 В, которые
добавляют к общему потреблению.
И получились вот такие цифры:
Сетевой кабель не подключён: 0.72 Вт.
Линк 1 гигабит: 1.92 Вт / Тест скорости: 1.94 Вт.
Линк 2.5 гигабит: 2.51 Вт / Тест скорости: 2.62 Вт.
Линк 5 гигабит: 2.78 Вт / Тест скорости: 2.82 Вт.

Стр.  25

Выводы и кому это надо
Если искать кейсы, где 5 Гбит сеть будет полезна, то я вижу такое:
У меня уже есть сеть 10 Гбит, но я хочу дешёвый и не горячий апгрейд для клиентов.
Стоимость 5GbE карты в 3–5 раз ниже, чем у современной 10GbE карты, а тепловыделение
кратно ниже старых решений типа X540 t2. В таком случае 5GbE можно назвать золотой
серединой между скоростью, ценой и потреблением.
Прямое подключение клиентов. Например, пара серверов в кластере или один быстрый
клиент для NAS. А может быть, подключение быстрой Wi-Fi точки к NAS. Всего пара тысяч
рублей, и вместо стандартного гигабита наш клиент уже общается на 5 гигабитах.
Апгрейд сети до 2,5GbE с заделом на будущее. Свичи на 2,5 гигабита сейчас стоят сущие
копейки, а 2,5 и 5GbE карты стоят идентично. Так почему бы не построить быструю сеть с
заделом на будущее на картах 5GbE, которая ни рублём не дороже, чем сеть с картами
2,5GbE?
К самому стандарту вопросов нет. Всё без каких-либо проблем работает в размерах 2-3-
комнатной квартиры на старых-добрых CAT5E кабелях. Стабильность работы карт Realtek
отличная, никаких проблем (кроме перегрева конкретно моего экземпляра) я не нашёл.
Кстати, я завёл Telegram-канал Tiralab. Там — спойлеры к статьям, полезные ссылки и тесты
разного железа. Если вам интересны хоумлаб и эксперименты с оборудованием, добро
пожаловать!
© 2026 ООО «МТ ФИНАНС»

In [44]:
pdf_document = r"PDF-Copy1\\Изучаем 5GBE-сети _ Хабр.pdf"
doc = fitz.open(pdf_document)
print("Исходный документ: ", doc)
text = []
for current_page in range(len(doc)):
    page = doc.load_page(current_page)
    page_text = page.get_text("text")
    text.append(page_text)
    print(page_text)

Исходный документ:  Document('PDF-Copy1\\Изучаем 5GBE-сети _ Хабр.pdf')
3031.1
Общий рейтинг
RUVDS.com
VDS/VPS-хостинг. Скидка 15% по коду HABR15
Подписаться
Какое железо есть на рынке
Стандарт 5 Гбит очень новый, ему буквально несколько лет, поэтому чипов, которые его
поддерживают, совсем немного, но они всё же есть.
Если говорить про нативную PCIE карту, которая поддерживает максимум 5GbE, то есть аж 2
варианта:
Marvell AQtion AQC111C.
Realtek RTL8126.
Marvell AQC111C
Решение от Marvell AQC111C интересно тем, что иногда выпускается в конфигурации аж на 4
порта, есть также карты и на 1 порт. Судя по тестам в сети, уровень потребления и нагрева
немного выше, чем у решения от Realtek. К сожалению, для РФ этот вариант можно сразу
вычёркивать, так как купить его на маркетплейсах просто невозможно, а за рубежом цены
сильно выше, чем у конкурента.
Tirarex 1 час назад
Изучаем 5GBE-сети
Простой
7 мин
2.3K
Блог компании RUVDS.com, Сетевое оборудование, Сетевые технологии*, Серверное администрирование*
Обзор
Все потоки
Узнали, сколько получают в IT
Войти

Сюда же впишу QC111U, это тот же чип от «Марвел», но уже с USB интерфейсом. На его основе
уже выпущены USB донглы, даже у вполне именитых в узких кругах фирм, таких как, например,
StarTech и TRENDnet. Но в целом ситуация схожа с PCIE решением от этой же фирмы. Чип
дороже, немного горячее, и в РФ его не купить. На ServeTheHome даже есть обзор нескольких
таких донглов.
(источник https://au.world.taobao.com/item/RHhGTjFhc3FobkhRZ2Flejc1TGh2UT09.htm)
Realtek RTL8126
Решение Realtek RTL8126 уже намного интереснее, банально благодаря широкому
распространению на маркетплейсах РФ и ужасно низкой цене (примерно 850–100 рублей за
сетевую карту на один порт). Чип не горячий, поэтому при наличии небольшого радиатора можно
сказать, что обдува он не требует.

(источник — магазин OZON)
При этом он получил какую-то неслыханную любовь в Китае, без каких-либо проблем можно
найти сетевые карты в m.2 формате с ключами A+E и B+M и т. д.
Таким образом можно заменить Wi-Fi модуль на проводную сеть 5 Гбит или поставить сетевую
карту в свободный слот для обычных SSD дисков формата 2280. Это, как по мне, очень крутой
бонус для маленьких ПК и даже ноутбуков.

Отдельно хочется отметить интерфейс подключения, ведь это PCIE 3-й версии и всего 1 линия!
Таким образом, эти карты можно ставить в тот самый X1 слот, который обычно стоит без дела.
Realtek RTL8157
Владельцев ноутбуков тоже не обделили. У «Риалтека» есть чип RTL8157, который
поддерживает 5GbE сеть через USB соединение. Для работы требуется абсолютно обычный, я
бы сказал, уже старый и добрый USB 3 порт на скорости 5 Гбит/сек.
Естественно, скорость будет немного ниже, а пинг выше из-за задержек USB стека, но в целом
это, наверное, самое оптимальное решение для получения высоких скоростей на ноутбуке без
какого-либо вмешательства в его железо.
При этом всём стоимость этого решения очень демократичная:

А их уже куда-то ставят?
На удивление, да! Несмотря на новизну стандарта, в том же DNS можно найти много плат с
поддержкой сети 5GbE. Буквально все они используют чип RTL8126, так как он банально без
особых доработок встаёт на место RTL8125. Конечно, большинство этих плат из среднего-
высокого ценового сегмента, но, если смотреть на цену самого чипа, вопрос его появления в
бюджетных платах — лишь вопрос времени.
(источник — магазин DNS)
Свичи
Их, можно сказать, что нет, и это на данный момент самая большая проблема.

В середине 2025 года на Computex был показан свич SR-S5G3008, но на практике найти его в
продаже мне пока не удалось.
Также недавно на рынке появился NICGIGA S50-0800 за 169 $, и на него есть обзор на
ServeTheHome.
Но, смотря на строение свича, я бы провёл аналогию с 2.5GbE свичами на момент их
зарождения. Это Gen1 свич, где каждый порт использует отдельную микросхему, а объединяет
их RTL9303, решение на 10 Гбит, которое тут работает в полсилы.
В отличии от Gen2 решений, где весь свич использует одну микросхему, эта компоновка требует
больше питания, и, соответственно, греется сильнее.

(Пример GEn2 свича стандарта 2.5GbE, источник https://www.acwifi.net/24353.html)
Если провести аналогию со свичами на стандарте 2,5GbE, то мы сейчас где-то в паре лет от
появления дешёвых и энергоэффективных 5GbE свичей.
Обратная совместимость
С обратной совместимостью всё неплохо, но только если у вас свежее 10GbE железо. Старые
контроллеры, изготовленные до стандарта 802.3bz (примерно все до 2016 года), банально не
заработают на стандарте 5GbE и 2.5GbE.
Например, такие контроллеры, как:
Intel X540.
Intel X550 старых ревизий.
Intel 82599 не смогут согласовать 5 Гбит и будут работать на скорости 1 Гбит/сек.
Но более свежие контроллеры типа X710 или нового RTL8127 без проблем смогут работать на
стандарте 5 Гбит.
С 10G SFP+ на ETH адаптерами ситуация идентичная, нужно искать более свежие адаптеры, на
которых указано, что есть поддержка 5 Гбит линка. Но на практике, если указано, что работает
стандарт 2,5 Гбит, то с шансом 99 % будет работать и 5 Гбит.

Что купил я
На синем маркетплейсе было взято 2 сетевых карты без бренда, по цене 1000руб/шт. Ради
интереса я брал самые простые карты без радиаторов охлаждения, дабы понять, как это всё
будет греться.
На практике мне пришли карты с брендированием IOCREST. В комплекте была инструкция и 2
планки разных размеров.

Чего-то особого про карту сказать не получится. На плате чип Realtek RTL8126, пара
преобразователей питания, чип памяти с прошивкой и трансформатор с сетевым портом. Планку
можно поменять на низкопрофильную (2U), но на практике, если планку снять, то карта влезает
в 1U сервер вертикально.
Забегая вперёд, скажу, что стоит брать карту с охлаждением, так как при работе на
максимальных скоростях эта карта перегревается и троттлит.



Запуск в Proxmox
После установки карты и запуска сервера Proxmox не имел сеть. Как обычно, ID адаптера
сменился с enpXs0 на enpX+1s0, ведь мы поставили новое устройство. После правки файла с
настройками сетевых интерфейсов я так и не увидел новый сетевой порт.
Дело в том, что чип Realtek 8126 очень новый, и драйвер под него появился только в ядре 6.14, а
моя система работает на ядре 6.13. Удачно совпало, что на момент экспериментов вышел
Proxmox 9 с ядром 6.14, и можно совместить неприятное с болезненным и обновить как сам
Proxmox, так и ядро.
Процесс обновления подробно описывать не стану, действовал по инструкции
https://pve.proxmox.com/wiki/Upgrade_from_8_to_9, обновление было сломано пакетом
докера, который я ставил очень давно, и это вообще неправда. apt fix broken install решил
удалить proxmox ve пакеты, в общем, ситуация схожая с той самой «steam install remove my
de». Ремонтировать это всё не стал, ведь Proxmox — это не про жёсткую привязку к текущей
установке. Забекапил все виртуальные машины, переустановил систему из свежего ISO
образа с официального сайта и развернул бекап обратно. Благо 10 Гбит сеть тут не просто
так, и на всё ушло меньше часа.

В остальном на свежем Proxmox 9 версии никаких проблем нет. Устройство видится с
нормальным названием (если у вас нет приписки про 5GbE контроллер, то драйвера нет).
Порт 5GbE карты закинул в бридж, воткнул в него кабель до свича, Proxmox сразу получил свой
IP и веб морда работает без проблем.
Подключаем кабель, вызываем ethtool eth0  и видим, что адаптер поддерживает и все
стандарты до 5 Гбит включительно, а также без проблем заработал на скорости 5 Гбит.

В целом, если у вас на сервере стоит «Линукс» со свежим ядром, то установка карты буквально
PlugNPlay.
Запуск в Windows
Сразу после запуска системы (Windows 11 24H2 - 26100.4946) сеть заработала без установки
каких-либо дополнительных драйверов и без ручных настроек. IP получен, линк 5 Гбит, и
Windows это прекрасно видит.

Запуск в TrueNAS
Всё не так однозначно. В версии Fangtooth (25.4) и выше драйвер уже есть из коробки, карта
после установки видна и без проблем работает.
Для более старых версий понадобится произвести процесс танца с бубном по установке
драйвера, который описан тут.
Тесты — в браузере — неудачные
Первым делом я решил прогнать обычный speed test между моим основным ПК (Windows 11
24h2) и Proxmox сервером (порт 5GbE в бридже с основным портом 2.5GbE, Proxmox 9, speed
test живёт в докере, докер в виртуалке «Убунты» с 4 ядрами и 8 ГБ оперативной памяти).
Результат из коробки на стоковых настройках можно лицезреть ниже. До 5 Гбит не дотягивает, но
уже выше, чем младший стандарт в 2,5 Гбит.

Пробуем поднять скорость методом настройки.
В Windows меняю MTU на 9000. Сделать это можно в настройках устройства в диспетчере
устройств. Пункт называется «большой кадр», и выставить его надо на 9014 байт.
В Proxmox делаем то же самое со всеми интерфейсами, а потом с бриджем.

И после теста получаем результат даже хуже, чем было раньше...
Тесты — в браузере — удачные
Я провёл много тестов, менял провода, менял MTU, настройки виртуальной машины и даже
гонял тесты на Baremetal, а не виртуалке, но в итоге проблема была в Firefox, банально тест
скорости в «Огнелисе» показывает меньшие результаты, чем в хроме.

Тесты — Iperf3
Обычный тест (iperf3 -c ipсервера -t 60 -P 16) показал 4,75 Гбит/сек, но результат был
нестабилен и падал вплоть до 1,4 Гбит.
Проблема была простая — перегрев сетевой карты. К сожалению, китайцы пожалели даже
крошечный радиатор, и плата на полной скорости может работать около 2 минут, после чего
начинает троттлить.
Нагрев через тепловизор выглядит так. Видно, что греется сам чип Realtek и один из
преобразователей питания. Троттлинг начинается при достижении 60 градусов на чипе.
Небольшой обдув за счёт корпусного вентилятора полностью решает проблему перегрева, но в
будущем я бы брал карту с радиатором.

Но стоит дать даже минимальный обдув (закрыл крышку сервера, и вентиляторы начали
минимально обдувать карту) — и скорость сразу стабилизируется на 4,75 Гбит без просадок.

Тот же тест, но в обратную сторону показал идентичную скорость в 4,74 Гбит/сек. Тут значение
MTU стоит на стандартных 1500, так как если ставить 9000, скорость упадёт до 3,4 Гбит/сек.

Тесты — Реальные скорости
Тесты выше показывали, как работает сама сеть, но какие же реальные цифры будут при записи
файлов по такой сети?
Для этого я расшарил папку на виртуалке с Windows (стоит на GEN4 X4 SSD диске «Самсунг») и
провёл тесты CrystalDiskInfo.
Результаты мне нравятся. При хорошем NVMe диске на сервере можно добиться результатов
уровня SATA SSD дисков. Мелкоблочные результаты, конечно, не впечатляют, это можно
отстроить, сделав NAS отдельной железкой и тонко подстроив параметры, но это уже тема для
отдельной статьи.

Копирование тестового файла в 40 ГБ не вызывает никаких вопросов. Скорость колеблется в
районе 560–570 мегабайт в секунду, что конвертируется в 4,8–4,9 Гбит/сек.


Потребление
Для тестов потребления я подключил карту с RTL8126 через PCIE X1 рейзер, а рейзер запитал
через тестер KM003C. На рейзере 2 преобразователя напряжений для 5 и 3,3 В, которые
добавляют к общему потреблению.
И получились вот такие цифры:
Сетевой кабель не подключён: 0.72 Вт.
Линк 1 гигабит: 1.92 Вт / Тест скорости: 1.94 Вт.
Линк 2.5 гигабит: 2.51 Вт / Тест скорости: 2.62 Вт.
Линк 5 гигабит: 2.78 Вт / Тест скорости: 2.82 Вт.

Выводы и кому это надо
Если искать кейсы, где 5 Гбит сеть будет полезна, то я вижу такое:
У меня уже есть сеть 10 Гбит, но я хочу дешёвый и не горячий апгрейд для клиентов.
Стоимость 5GbE карты в 3–5 раз ниже, чем у современной 10GbE карты, а тепловыделение
кратно ниже старых решений типа X540 t2. В таком случае 5GbE можно назвать золотой
серединой между скоростью, ценой и потреблением.
Прямое подключение клиентов. Например, пара серверов в кластере или один быстрый
клиент для NAS. А может быть, подключение быстрой Wi-Fi точки к NAS. Всего пара тысяч
рублей, и вместо стандартного гигабита наш клиент уже общается на 5 гигабитах.
Апгрейд сети до 2,5GbE с заделом на будущее. Свичи на 2,5 гигабита сейчас стоят сущие
копейки, а 2,5 и 5GbE карты стоят идентично. Так почему бы не построить быструю сеть с
заделом на будущее на картах 5GbE, которая ни рублём не дороже, чем сеть с картами
2,5GbE?
К самому стандарту вопросов нет. Всё без каких-либо проблем работает в размерах 2-3-
комнатной квартиры на старых-добрых CAT5E кабелях. Стабильность работы карт Realtek
отличная, никаких проблем (кроме перегрева конкретно моего экземпляра) я не нашёл.
Кстати, я завёл Telegram-канал Tiralab. Там — спойлеры к статьям, полезные ссылки и тесты
разного железа. Если вам интересны хоумлаб и эксперименты с оборудованием, добро
пожаловать!
© 2026 ООО «МТ ФИНАНС»

In [45]:
text = ''.join(text).replace('\n',' ')

In [46]:
text

'3031.1 Общий рейтинг RUVDS.com VDS/VPS-хостинг. Скидка 15% по коду HABR15 Подписаться Какое железо есть на рынке Стандарт 5 Гбит очень новый, ему буквально несколько лет, поэтому чипов, которые его поддерживают, совсем немного, но они всё же есть. Если говорить про нативную PCIE карту, которая поддерживает максимум 5GbE, то есть аж 2 варианта: Marvell AQtion AQC111C. Realtek RTL8126. Marvell AQC111C Решение от Marvell AQC111C интересно тем, что иногда выпускается в конфигурации аж на 4 порта, есть также карты и на 1 порт. Судя по тестам в сети, уровень потребления и нагрева немного выше, чем у решения от Realtek. К сожалению, для РФ этот вариант можно сразу вычёркивать, так как купить его на маркетплейсах просто невозможно, а за рубежом цены сильно выше, чем у конкурента. Tirarex 1 час назад Изучаем 5GBE-сети Простой 7 мин 2.3K Блог компании RUVDS.com,\xa0Сетевое оборудование,\xa0Сетевые технологии*,\xa0Серверное администрирование* Обзор Все потоки Узнали, сколько получают в IT Войти Сюда же впишу QC111U, это тот же чип от «Марвел», но уже с USB интерфейсом. На его основе уже выпущены USB донглы, даже у вполне именитых в узких кругах фирм, таких как, например, StarTech и TRENDnet. Но в целом ситуация схожа с PCIE решением от этой же фирмы. Чип дороже, немного горячее, и в РФ его не купить. На ServeTheHome даже есть обзор нескольких таких донглов. (источник https://au.world.taobao.com/item/RHhGTjFhc3FobkhRZ2Flejc1TGh2UT09.htm) Realtek RTL8126 Решение Realtek RTL8126 уже намного интереснее, банально благодаря широкому распространению на маркетплейсах РФ и ужасно низкой цене (примерно 850–100 рублей за сетевую карту на один порт). Чип не горячий, поэтому при наличии небольшого радиатора можно сказать, что обдува он не требует. (источник — магазин OZON) При этом он получил какую-то неслыханную любовь в Китае, без каких-либо проблем можно найти сетевые карты в m.2 формате с ключами A+E и B+M и т. д. Таким образом можно заменить Wi-Fi модуль на проводную сеть 5 Гбит или поставить сетевую карту в свободный слот для обычных SSD дисков формата 2280. Это, как по мне, очень крутой бонус для маленьких ПК и даже ноутбуков. Отдельно хочется отметить интерфейс подключения, ведь это PCIE 3-й версии и всего 1 линия! Таким образом, эти карты можно ставить в тот самый X1 слот, который обычно стоит без дела. Realtek RTL8157 Владельцев ноутбуков тоже не обделили. У «Риалтека» есть чип RTL8157, который поддерживает 5GbE сеть через USB соединение. Для работы требуется абсолютно обычный, я бы сказал, уже старый и добрый USB 3 порт на скорости 5 Гбит/сек. Естественно, скорость будет немного ниже, а пинг выше из-за задержек USB стека, но в целом это, наверное, самое оптимальное решение для получения высоких скоростей на ноутбуке без какого-либо вмешательства в его железо. При этом всём стоимость этого решения очень демократичная: А их уже куда-то ставят? На удивление, да! Несмотря на новизну стандарта, в том же DNS можно найти много плат с поддержкой сети 5GbE. Буквально все они используют чип RTL8126, так как он банально без особых доработок встаёт на место RTL8125. Конечно, большинство этих плат из среднего- высокого ценового сегмента, но, если смотреть на цену самого чипа, вопрос его появления в бюджетных платах — лишь вопрос времени. (источник — магазин DNS) Свичи Их, можно сказать, что нет, и это на данный момент самая большая проблема. В середине 2025 года на Computex был показан свич SR-S5G3008, но на практике найти его в продаже мне пока не удалось. Также недавно на рынке появился NICGIGA S50-0800 за 169 $, и на него есть обзор на ServeTheHome. Но, смотря на строение свича, я бы провёл аналогию с 2.5GbE свичами на момент их зарождения. Это Gen1 свич, где каждый порт использует отдельную микросхему, а объединяет их RTL9303, решение на 10 Гбит, которое тут работает в полсилы. В отличии от Gen2 решений, где весь свич использует одну микросхему, эта компоновка требует больше питания, и, соответственно, греется сильнее. (Пример GEn2 свича стандарта 2.5GbE, источник https://www.acwifi.net/24353.html) Если провести аналогию со свичами на стандарте 2,5GbE, то мы сейчас где-то в паре лет от появления дешёвых и энергоэффективных 5GbE свичей. Обратная совместимость С обратной совместимостью всё неплохо, но только если у вас свежее 10GbE железо. Старые контроллеры, изготовленные до стандарта 802.3bz (примерно все до 2016 года), банально не заработают на стандарте 5GbE и 2.5GbE. Например, такие контроллеры, как: Intel X540. Intel X550 старых ревизий. Intel 82599 не смогут согласовать 5 Гбит и будут работать на скорости 1 Гбит/сек. Но более свежие контроллеры типа X710 или нового RTL8127 без проблем смогут работать на стандарте 5 Гбит. С 10G SFP+ на ETH адаптерами ситуация идентичная, нужно искать более свежие адаптеры, на которых указано, что есть поддержка 5 Гбит линка. Но на практике, если указано, что работает стандарт 2,5 Гбит, то с шансом 99 % будет работать и 5 Гбит. Что купил я На синем маркетплейсе было взято 2 сетевых карты без бренда, по цене 1000руб/шт. Ради интереса я брал самые простые карты без радиаторов охлаждения, дабы понять, как это всё будет греться. На практике мне пришли карты с брендированием IOCREST. В комплекте была инструкция и 2 планки разных размеров. Чего-то особого про карту сказать не получится. На плате чип Realtek RTL8126, пара преобразователей питания, чип памяти с прошивкой и трансформатор с сетевым портом. Планку можно поменять на низкопрофильную (2U), но на практике, если планку снять, то карта влезает в 1U сервер вертикально. Забегая вперёд, скажу, что стоит брать карту с охлаждением, так как при работе на максимальных скоростях эта карта перегревается и троттлит. Запуск в Proxmox После установки карты и запуска сервера Proxmox не имел сеть. Как обычно, ID адаптера сменился с enpXs0 на enpX+1s0, ведь мы поставили новое устройство. После правки файла с настройками сетевых интерфейсов я так и не увидел новый сетевой порт. Дело в том, что чип Realtek 8126 очень новый, и драйвер под него появился только в ядре 6.14, а моя система работает на ядре 6.13. Удачно совпало, что на момент экспериментов вышел Proxmox 9 с ядром 6.14, и можно совместить неприятное с болезненным и обновить как сам Proxmox, так и ядро. Процесс обновления подробно описывать не стану, действовал по инструкции https://pve.proxmox.com/wiki/Upgrade_from_8_to_9, обновление было сломано пакетом докера, который я ставил очень давно, и это вообще неправда. apt fix broken install решил удалить proxmox ve пакеты, в общем, ситуация схожая с той самой «steam install remove my de». Ремонтировать это всё не стал, ведь Proxmox — это не про жёсткую привязку к текущей установке. Забекапил все виртуальные машины, переустановил систему из свежего ISO образа с официального сайта и развернул бекап обратно. Благо 10 Гбит сеть тут не просто так, и на всё ушло меньше часа. В остальном на свежем Proxmox 9 версии никаких проблем нет. Устройство видится с нормальным названием (если у вас нет приписки про 5GbE контроллер, то драйвера нет). Порт 5GbE карты закинул в бридж, воткнул в него кабель до свича, Proxmox сразу получил свой IP и веб морда работает без проблем. Подключаем кабель, вызываем ethtool eth0  и видим, что адаптер поддерживает и все стандарты до 5 Гбит включительно, а также без проблем заработал на скорости 5 Гбит. В целом, если у вас на сервере стоит «Линукс» со свежим ядром, то установка карты буквально PlugNPlay. Запуск в Windows Сразу после запуска системы (Windows 11 24H2 - 26100.4946) сеть заработала без установки каких-либо дополнительных драйверов и без ручных настроек. IP получен, линк 5 Гбит, и Windows это прекрасно видит. Запуск в TrueNAS Всё не так однозначно. В версии Fangtooth (25.4) и выше драйвер уже есть из коробки, карта после установки видна и без проблем работает. Для более старых версий понадобится произвести процесс танца с бубном по установке драйвера, который описан тут. Тесты — в браузере — неудачные Первым делом я решил прогнать обычный speed test между моим основным ПК (Windows 11 24h2) и Proxmox сервером (порт 5GbE в бридже с основным портом 2.5GbE, Proxmox 9, speed test живёт в докере, докер в виртуалке «Убунты» с 4 ядрами и 8 ГБ оперативной памяти). Результат из коробки на стоковых настройках можно лицезреть ниже. До 5 Гбит не дотягивает, но уже выше, чем младший стандарт в 2,5 Гбит. Пробуем поднять скорость методом настройки. В Windows меняю MTU на 9000. Сделать это можно в настройках устройства в диспетчере устройств. Пункт называется «большой кадр», и выставить его надо на 9014 байт. В Proxmox делаем то же самое со всеми интерфейсами, а потом с бриджем. И после теста получаем результат даже хуже, чем было раньше... Тесты — в браузере — удачные Я провёл много тестов, менял провода, менял MTU, настройки виртуальной машины и даже гонял тесты на Baremetal, а не виртуалке, но в итоге проблема была в Firefox, банально тест скорости в «Огнелисе» показывает меньшие результаты, чем в хроме. Тесты — Iperf3 Обычный тест (iperf3 -c ipсервера -t 60 -P 16) показал 4,75 Гбит/сек, но результат был нестабилен и падал вплоть до 1,4 Гбит. Проблема была простая — перегрев сетевой карты. К сожалению, китайцы пожалели даже крошечный радиатор, и плата на полной скорости может работать около 2 минут, после чего начинает троттлить. Нагрев через тепловизор выглядит так. Видно, что греется сам чип Realtek и один из преобразователей питания. Троттлинг начинается при достижении 60 градусов на чипе. Небольшой обдув за счёт корпусного вентилятора полностью решает проблему перегрева, но в будущем я бы брал карту с радиатором. Но стоит дать даже минимальный обдув (закрыл крышку сервера, и вентиляторы начали минимально обдувать карту) — и скорость сразу стабилизируется на 4,75 Гбит без просадок. Тот же тест, но в обратную сторону показал идентичную скорость в 4,74 Гбит/сек. Тут значение MTU стоит на стандартных 1500, так как если ставить 9000, скорость упадёт до 3,4 Гбит/сек. Тесты — Реальные скорости Тесты выше показывали, как работает сама сеть, но какие же реальные цифры будут при записи файлов по такой сети? Для этого я расшарил папку на виртуалке с Windows (стоит на GEN4 X4 SSD диске «Самсунг») и провёл тесты CrystalDiskInfo. Результаты мне нравятся. При хорошем NVMe диске на сервере можно добиться результатов уровня SATA SSD дисков. Мелкоблочные результаты, конечно, не впечатляют, это можно отстроить, сделав NAS отдельной железкой и тонко подстроив параметры, но это уже тема для отдельной статьи. Копирование тестового файла в 40 ГБ не вызывает никаких вопросов. Скорость колеблется в районе 560–570 мегабайт в секунду, что конвертируется в 4,8–4,9 Гбит/сек. Потребление Для тестов потребления я подключил карту с RTL8126 через PCIE X1 рейзер, а рейзер запитал через тестер KM003C. На рейзере 2 преобразователя напряжений для 5 и 3,3 В, которые добавляют к общему потреблению. И получились вот такие цифры: Сетевой кабель не подключён: 0.72 Вт. Линк 1 гигабит: 1.92 Вт / Тест скорости: 1.94 Вт. Линк 2.5 гигабит: 2.51 Вт / Тест скорости: 2.62 Вт. Линк 5 гигабит: 2.78 Вт / Тест скорости: 2.82 Вт. Выводы и кому это надо Если искать кейсы, где 5 Гбит сеть будет полезна, то я вижу такое: У меня уже есть сеть 10 Гбит, но я хочу дешёвый и не горячий апгрейд для клиентов. Стоимость 5GbE карты в 3–5 раз ниже, чем у современной 10GbE карты, а тепловыделение кратно ниже старых решений типа X540 t2. В таком случае 5GbE можно назвать золотой серединой между скоростью, ценой и потреблением. Прямое подключение клиентов. Например, пара серверов в кластере или один быстрый клиент для NAS. А может быть, подключение быстрой Wi-Fi точки к NAS. Всего пара тысяч рублей, и вместо стандартного гигабита наш клиент уже общается на 5 гигабитах. Апгрейд сети до 2,5GbE с заделом на будущее. Свичи на 2,5 гигабита сейчас стоят сущие копейки, а 2,5 и 5GbE карты стоят идентично. Так почему бы не построить быструю сеть с заделом на будущее на картах 5GbE, которая ни рублём не дороже, чем сеть с картами 2,5GbE? К самому стандарту вопросов нет. Всё без каких-либо проблем работает в размерах 2-3- комнатной квартиры на старых-добрых CAT5E кабелях. Стабильность работы карт Realtek отличная, никаких проблем (кроме перегрева конкретно моего экземпляра) я не нашёл. Кстати, я завёл Telegram-канал Tiralab. Там — спойлеры к статьям, полезные ссылки и тесты разного железа. Если вам интересны хоумлаб и эксперименты с оборудованием, добро пожаловать! © 2026 ООО «МТ ФИНАНС» '

In [85]:
def extract_text_from_pdf(pdf_path):
    doc = fitz.open(pdf_path)
    text = [page.get_text("text") for page in doc]
    doc.close()
    return text

In [86]:
def get_file_date(pdf_path):
    ts = os.path.getmtime(pdf_path)
    return datetime.datetime.fromtimestamp(ts)

In [91]:
def pars_pdf(pages, file_dt):
    if not pages:
        return "Unknown", "", "", file_dt.strftime('%d.%m.%Y')
    full_text = " ".join(pages[:2]).replace('\xa0', ' ')
    full_text = re.sub(r'\s+', ' ', full_text)
    
    name, rating, activity, date_pub = "Unknown", "", "", ""
    
    r_match = re.search(r'(\d+[.,]\d+)\s+Общий рейтинг', full_text)
    if r_match:
        rating = r_match.group(1).replace(',', '.')

    meta_match = re.search(r'Общий рейтинг\s+(.*?)\s+(?=Подписаться|Читать|Обзор|Все потоки)', full_text)
    
    if meta_match:
        content = meta_match.group(1).strip()
        parts = content.split(' ', 1) 
        if len(parts) > 0:
            known_brands = ['Timeweb Cloud', 'Positive Technologies', 'Online patent', 'Альфа-Банк', 'ЮMoney', 'RUVDS.com']
            found_brand = False
            for brand in known_brands:
                if content.startswith(brand):
                    name = brand
                    activity = content.replace(brand, '').strip()
                    found_brand = True
                    break
            
            if not found_brand:
                name = parts[0]
                activity = parts[1] if len(parts) > 1 else ""

    if "VDS/VPS" in name or "скидка" in name.lower():
        name_fix = re.search(r'([A-Za-z0-9.-]+\.(com|ru|net))', full_text)
        if name_fix:
            name = name_fix.group(1)

    months = {'янв':1,'фев':2,'мар':3,'апр':4,'май':5,'июн':6,'июл':7,'авг':8,'сен':9,'окт':10,'ноя':11,'дек':12,
              'января':1,'февраля':2,'марта':3,'апреля':4,'мая':5,'июня':6,'июля':7,'августа':8,'сентября':9,'октября':10,'ноября':11,'декабря':12}
    
    date_match = re.search(r'(\d+)\s+(час|мин|ден|дня|дней)\w*\s+назад|вчера', full_text.lower())
    if date_match:
        found = date_match.group(0)
        n = re.findall(r'\d+', found)
        num = int(n[0]) if n else 1
        if 'час' in found: date_pub = (file_dt - timedelta(hours=num)).strftime('%d.%m.%Y')
        elif 'вчера' in found: date_pub = (file_dt - timedelta(days=1)).strftime('%d.%m.%Y')
        else: date_pub = (file_dt - timedelta(days=num)).strftime('%d.%m.%Y')
    else:
        fix = re.search(rf'(\d{{1,2}})\s+({ "|".join(months.keys()) })', full_text.lower())
        if fix:
            d, m_str = int(fix[1]), fix[2][:3]
            y = file_dt.year
            if months[m_str] > file_dt.month: y -= 1
            date_pub = f"{d:02d}.{months[m_str]:02d}.{y}"

    if not date_pub: date_pub = file_dt.strftime('%d.%m.%Y')

    return name, rating, activity, date_pub

In [92]:
x = extract_text_from_pdf(r"PDF-Copy1\\Изучаем 5GBE-сети _ Хабр.pdf")

In [93]:
x

['3031.1\nОбщий рейтинг\nRUVDS.com\nVDS/VPS-хостинг. Скидка 15% по коду HABR15\nПодписаться\nКакое железо есть на рынке\nСтандарт 5 Гбит очень новый, ему буквально несколько лет, поэтому чипов, которые его\nподдерживают, совсем немного, но они всё же есть.\nЕсли говорить про нативную PCIE карту, которая поддерживает максимум 5GbE, то есть аж 2\nварианта:\nMarvell AQtion AQC111C.\nRealtek RTL8126.\nMarvell AQC111C\nРешение от Marvell AQC111C интересно тем, что иногда выпускается в конфигурации аж на 4\nпорта, есть также карты и на 1 порт. Судя по тестам в сети, уровень потребления и нагрева\nнемного выше, чем у решения от Realtek. К сожалению, для РФ этот вариант можно сразу\nвычёркивать, так как купить его на маркетплейсах просто невозможно, а за рубежом цены\nсильно выше, чем у конкурента.\nTirarex 1 час назад\nИзучаем 5GBE-сети\nПростой\n7 мин\n2.3K\nБлог компании RUVDS.com,\xa0Сетевое оборудование,\xa0Сетевые технологии*,\xa0Серверное администрирование*\nОбзор\nВсе потоки\nУзнали, сколько получают в IT\nВойти\n',
 'Сюда же впишу QC111U, это тот же чип от «Марвел», но уже с USB интерфейсом. На его основе\nуже выпущены USB донглы, даже у вполне именитых в узких кругах фирм, таких как, например,\nStarTech и TRENDnet. Но в целом ситуация схожа с PCIE решением от этой же фирмы. Чип\nдороже, немного горячее, и в РФ его не купить. На ServeTheHome даже есть обзор нескольких\nтаких донглов.\n(источник https://au.world.taobao.com/item/RHhGTjFhc3FobkhRZ2Flejc1TGh2UT09.htm)\nRealtek RTL8126\nРешение Realtek RTL8126 уже намного интереснее, банально благодаря широкому\nраспространению на маркетплейсах РФ и ужасно низкой цене (примерно 850–100 рублей за\nсетевую карту на один порт). Чип не горячий, поэтому при наличии небольшого радиатора можно\nсказать, что обдува он не требует.\n',
 '(источник — магазин OZON)\nПри этом он получил какую-то неслыханную любовь в Китае, без каких-либо проблем можно\nнайти сетевые карты в m.2 формате с ключами A+E и B+M и т. д.\nТаким образом можно заменить Wi-Fi модуль на проводную сеть 5 Гбит или поставить сетевую\nкарту в свободный слот для обычных SSD дисков формата 2280. Это, как по мне, очень крутой\nбонус для маленьких ПК и даже ноутбуков.\n',
 'Отдельно хочется отметить интерфейс подключения, ведь это PCIE 3-й версии и всего 1 линия!\nТаким образом, эти карты можно ставить в тот самый X1 слот, который обычно стоит без дела.\nRealtek RTL8157\nВладельцев ноутбуков тоже не обделили. У «Риалтека» есть чип RTL8157, который\nподдерживает 5GbE сеть через USB соединение. Для работы требуется абсолютно обычный, я\nбы сказал, уже старый и добрый USB 3 порт на скорости 5 Гбит/сек.\nЕстественно, скорость будет немного ниже, а пинг выше из-за задержек USB стека, но в целом\nэто, наверное, самое оптимальное решение для получения высоких скоростей на ноутбуке без\nкакого-либо вмешательства в его железо.\nПри этом всём стоимость этого решения очень демократичная:\n',
 'А их уже куда-то ставят?\nНа удивление, да! Несмотря на новизну стандарта, в том же DNS можно найти много плат с\nподдержкой сети 5GbE. Буквально все они используют чип RTL8126, так как он банально без\nособых доработок встаёт на место RTL8125. Конечно, большинство этих плат из среднего-\nвысокого ценового сегмента, но, если смотреть на цену самого чипа, вопрос его появления в\nбюджетных платах — лишь вопрос времени.\n(источник — магазин DNS)\nСвичи\nИх, можно сказать, что нет, и это на данный момент самая большая проблема.\n',
 'В середине 2025 года на Computex был показан свич SR-S5G3008, но на практике найти его в\nпродаже мне пока не удалось.\nТакже недавно на рынке появился NICGIGA S50-0800 за 169 $, и на него есть обзор на\nServeTheHome.\nНо, смотря на строение свича, я бы провёл аналогию с 2.5GbE свичами на момент их\nзарождения. Это Gen1 свич, где каждый порт использует отдельную микросхему, а объединяет\nих RTL9303, решение на 10 Гбит, которое тут работает в полсилы.\nВ отличии от Gen2 решений, где весь свич использует одну микросхему, эта компоновка требует\nбольше питания, и, соответственно, греется сильнее.\n',
 '(Пример GEn2 свича стандарта 2.5GbE, источник https://www.acwifi.net/24353.html)\nЕсли провести аналогию со свичами на стандарте 2,5GbE, то мы сейчас где-то в паре лет от\nпоявления дешёвых и энергоэффективных 5GbE свичей.\nОбратная совместимость\nС обратной совместимостью всё неплохо, но только если у вас свежее 10GbE железо. Старые\nконтроллеры, изготовленные до стандарта 802.3bz (примерно все до 2016 года), банально не\nзаработают на стандарте 5GbE и 2.5GbE.\nНапример, такие контроллеры, как:\nIntel X540.\nIntel X550 старых ревизий.\nIntel 82599 не смогут согласовать 5 Гбит и будут работать на скорости 1 Гбит/сек.\nНо более свежие контроллеры типа X710 или нового RTL8127 без проблем смогут работать на\nстандарте 5 Гбит.\nС 10G SFP+ на ETH адаптерами ситуация идентичная, нужно искать более свежие адаптеры, на\nкоторых указано, что есть поддержка 5 Гбит линка. Но на практике, если указано, что работает\nстандарт 2,5 Гбит, то с шансом 99 % будет работать и 5 Гбит.\n',
 'Что купил я\nНа синем маркетплейсе было взято 2 сетевых карты без бренда, по цене 1000руб/шт. Ради\nинтереса я брал самые простые карты без радиаторов охлаждения, дабы понять, как это всё\nбудет греться.\nНа практике мне пришли карты с брендированием IOCREST. В комплекте была инструкция и 2\nпланки разных размеров.\n',
 'Чего-то особого про карту сказать не получится. На плате чип Realtek RTL8126, пара\nпреобразователей питания, чип памяти с прошивкой и трансформатор с сетевым портом. Планку\nможно поменять на низкопрофильную (2U), но на практике, если планку снять, то карта влезает\nв 1U сервер вертикально.\nЗабегая вперёд, скажу, что стоит брать карту с охлаждением, так как при работе на\nмаксимальных скоростях эта карта перегревается и троттлит.\n',
 '',
 '',
 'Запуск в Proxmox\nПосле установки карты и запуска сервера Proxmox не имел сеть. Как обычно, ID адаптера\nсменился с enpXs0 на enpX+1s0, ведь мы поставили новое устройство. После правки файла с\nнастройками сетевых интерфейсов я так и не увидел новый сетевой порт.\nДело в том, что чип Realtek 8126 очень новый, и драйвер под него появился только в ядре 6.14, а\nмоя система работает на ядре 6.13. Удачно совпало, что на момент экспериментов вышел\nProxmox 9 с ядром 6.14, и можно совместить неприятное с болезненным и обновить как сам\nProxmox, так и ядро.\nПроцесс обновления подробно описывать не стану, действовал по инструкции\nhttps://pve.proxmox.com/wiki/Upgrade_from_8_to_9, обновление было сломано пакетом\nдокера, который я ставил очень давно, и это вообще неправда. apt fix broken install решил\nудалить proxmox ve пакеты, в общем, ситуация схожая с той самой «steam install remove my\nde». Ремонтировать это всё не стал, ведь Proxmox — это не про жёсткую привязку к текущей\nустановке. Забекапил все виртуальные машины, переустановил систему из свежего ISO\nобраза с официального сайта и развернул бекап обратно. Благо 10 Гбит сеть тут не просто\nтак, и на всё ушло меньше часа.\n',
 'В остальном на свежем Proxmox 9 версии никаких проблем нет. Устройство видится с\nнормальным названием (если у вас нет приписки про 5GbE контроллер, то драйвера нет).\nПорт 5GbE карты закинул в бридж, воткнул в него кабель до свича, Proxmox сразу получил свой\nIP и веб морда работает без проблем.\nПодключаем кабель, вызываем ethtool eth0  и видим, что адаптер поддерживает и все\nстандарты до 5 Гбит включительно, а также без проблем заработал на скорости 5 Гбит.\n',
 'В целом, если у вас на сервере стоит «Линукс» со свежим ядром, то установка карты буквально\nPlugNPlay.\nЗапуск в Windows\nСразу после запуска системы (Windows 11 24H2 - 26100.4946) сеть заработала без установки\nкаких-либо дополнительных драйверов и без ручных настроек. IP получен, линк 5 Гбит, и\nWindows это прекрасно видит.\n',
 'Запуск в TrueNAS\nВсё не так однозначно. В версии Fangtooth (25.4) и выше драйвер уже есть из коробки, карта\nпосле установки видна и без проблем работает.\nДля более старых версий понадобится произвести процесс танца с бубном по установке\nдрайвера, который описан тут.\nТесты — в браузере — неудачные\nПервым делом я решил прогнать обычный speed test между моим основным ПК (Windows 11\n24h2) и Proxmox сервером (порт 5GbE в бридже с основным портом 2.5GbE, Proxmox 9, speed\ntest живёт в докере, докер в виртуалке «Убунты» с 4 ядрами и 8 ГБ оперативной памяти).\nРезультат из коробки на стоковых настройках можно лицезреть ниже. До 5 Гбит не дотягивает, но\nуже выше, чем младший стандарт в 2,5 Гбит.\n',
 'Пробуем поднять скорость методом настройки.\nВ Windows меняю MTU на 9000. Сделать это можно в настройках устройства в диспетчере\nустройств. Пункт называется «большой кадр», и выставить его надо на 9014 байт.\nВ Proxmox делаем то же самое со всеми интерфейсами, а потом с бриджем.\n',
 'И после теста получаем результат даже хуже, чем было раньше...\nТесты — в браузере — удачные\nЯ провёл много тестов, менял провода, менял MTU, настройки виртуальной машины и даже\nгонял тесты на Baremetal, а не виртуалке, но в итоге проблема была в Firefox, банально тест\nскорости в «Огнелисе» показывает меньшие результаты, чем в хроме.\n',
 'Тесты — Iperf3\nОбычный тест (iperf3 -c ipсервера -t 60 -P 16) показал 4,75 Гбит/сек, но результат был\nнестабилен и падал вплоть до 1,4 Гбит.\nПроблема была простая — перегрев сетевой карты. К сожалению, китайцы пожалели даже\nкрошечный радиатор, и плата на полной скорости может работать около 2 минут, после чего\nначинает троттлить.\nНагрев через тепловизор выглядит так. Видно, что греется сам чип Realtek и один из\nпреобразователей питания. Троттлинг начинается при достижении 60 градусов на чипе.\nНебольшой обдув за счёт корпусного вентилятора полностью решает проблему перегрева, но в\nбудущем я бы брал карту с радиатором.\n',
 'Но стоит дать даже минимальный обдув (закрыл крышку сервера, и вентиляторы начали\nминимально обдувать карту) — и скорость сразу стабилизируется на 4,75 Гбит без просадок.\n',
 'Тот же тест, но в обратную сторону показал идентичную скорость в 4,74 Гбит/сек. Тут значение\nMTU стоит на стандартных 1500, так как если ставить 9000, скорость упадёт до 3,4 Гбит/сек.\n',
 'Тесты — Реальные скорости\nТесты выше показывали, как работает сама сеть, но какие же реальные цифры будут при записи\nфайлов по такой сети?\nДля этого я расшарил папку на виртуалке с Windows (стоит на GEN4 X4 SSD диске «Самсунг») и\nпровёл тесты CrystalDiskInfo.\nРезультаты мне нравятся. При хорошем NVMe диске на сервере можно добиться результатов\nуровня SATA SSD дисков. Мелкоблочные результаты, конечно, не впечатляют, это можно\nотстроить, сделав NAS отдельной железкой и тонко подстроив параметры, но это уже тема для\nотдельной статьи.\n',
 'Копирование тестового файла в 40 ГБ не вызывает никаких вопросов. Скорость колеблется в\nрайоне 560–570 мегабайт в секунду, что конвертируется в 4,8–4,9 Гбит/сек.\n',
 '',
 'Потребление\nДля тестов потребления я подключил карту с RTL8126 через PCIE X1 рейзер, а рейзер запитал\nчерез тестер KM003C. На рейзере 2 преобразователя напряжений для 5 и 3,3 В, которые\nдобавляют к общему потреблению.\nИ получились вот такие цифры:\nСетевой кабель не подключён: 0.72 Вт.\nЛинк 1 гигабит: 1.92 Вт / Тест скорости: 1.94 Вт.\nЛинк 2.5 гигабит: 2.51 Вт / Тест скорости: 2.62 Вт.\nЛинк 5 гигабит: 2.78 Вт / Тест скорости: 2.82 Вт.\n',
 'Выводы и кому это надо\nЕсли искать кейсы, где 5 Гбит сеть будет полезна, то я вижу такое:\nУ меня уже есть сеть 10 Гбит, но я хочу дешёвый и не горячий апгрейд для клиентов.\nСтоимость 5GbE карты в 3–5 раз ниже, чем у современной 10GbE карты, а тепловыделение\nкратно ниже старых решений типа X540 t2. В таком случае 5GbE можно назвать золотой\nсерединой между скоростью, ценой и потреблением.\nПрямое подключение клиентов. Например, пара серверов в кластере или один быстрый\nклиент для NAS. А может быть, подключение быстрой Wi-Fi точки к NAS. Всего пара тысяч\nрублей, и вместо стандартного гигабита наш клиент уже общается на 5 гигабитах.\nАпгрейд сети до 2,5GbE с заделом на будущее. Свичи на 2,5 гигабита сейчас стоят сущие\nкопейки, а 2,5 и 5GbE карты стоят идентично. Так почему бы не построить быструю сеть с\nзаделом на будущее на картах 5GbE, которая ни рублём не дороже, чем сеть с картами\n2,5GbE?\nК самому стандарту вопросов нет. Всё без каких-либо проблем работает в размерах 2-3-\nкомнатной квартиры на старых-добрых CAT5E кабелях. Стабильность работы карт Realtek\nотличная, никаких проблем (кроме перегрева конкретно моего экземпляра) я не нашёл.\nКстати, я завёл Telegram-канал Tiralab. Там — спойлеры к статьям, полезные ссылки и тесты\nразного железа. Если вам интересны хоумлаб и эксперименты с оборудованием, добро\nпожаловать!\n© 2026 ООО «МТ ФИНАНС»\n']

In [95]:
import fitz
import re
import os
import datetime
from datetime import timedelta

Brak = []
NameCompany = []
Raiting = []
DataPublish = []
Activity = []
TextArticle = []
Description = [] 

for pdf_path in all_pdf:
    try:  
        content_pages = extract_text_from_pdf(pdf_path)
        f_date = get_file_date(pdf_path)
        
        N, R, A, D = pars_pdf(content_pages, f_date)
        
        full_raw_text = ' '.join(content_pages).replace('\xa0', ' ').replace('\n', ' ')
        full_raw_text = re.sub(r'\s+', ' ', full_raw_text)
        content_start = re.search(r'(Подписаться|Обзор|Все потоки|Войти)\s+', full_raw_text)
        
        if content_start:
            desc_text = full_raw_text[content_start.end():].strip()
        else:
            desc_text = full_raw_text.strip()
    
        NameCompany.append(N)
        Raiting.append(R)
        DataPublish.append(D)
        Activity.append(A)
        Description.append(desc_text) 
        TextArticle.append(full_raw_text) 
    
        print(f"OK: {pdf_path.split('\\')[-1]} -> {N}")
        
    except Exception as e:
        print(f"ОШИБКА на файле {pdf_path}: {e}")
        Brak.append(pdf_path)  
    except Exception as e:
        print(f"ОШИБКА на файле {pdf_path}: {e}")
        Brak.append(pdf_path)

print(f"\nИтог: Обработано {len(NameCompany)}, Ошибок {len(Brak)}")

OK: AI-диджей Spotify иногда не понимает даже простые музыкальные запросы _ Хабр.pdf -> NeyroHub
OK: Docker_Podman-клиент и Remote-клиент для GigaIDE _ Хабр.pdf -> Сбер
OK: Meta может сократить до 20% сотрудников на фоне роста расходов на AI _ Хабр.pdf -> NeyroHub
OK: Автоматизируем сканирование инфраструктуры_ скрипт 3.0 для Сканер-ВС 7 _ Хабр.pdf -> Selectel
OK: Генерация изображений в Nano Banana_ Промпты и гайд по использованию Gemini 3 Pro_Flash _ Хабр.pdf -> StudyAI
OK: Делимся опытом защиты и мониторинга безопасности медиахолдинга _ Хабр.pdf -> Бастион
OK: Изучаем 5GBE-сети _ Хабр.pdf -> RUVDS.com
OK: Как недорогой MacBook Neo за $600 меняет рынок ноутбуков на Windows _ Хабр.pdf -> МТС
OK: Как расти QA-инженеру_ инструменты, которые действительно работают _ Хабр.pdf -> AvitoTech
OK: Как создатель первой веб-камеры был вынужден продать все свои разработки_ история Connectix _ Хабр.pdf -> Online patent
OK: Как я делал эконом-вариант датчика качества воздуха для своего Home Assistant и что из этого вышло _ Хабр.pdf -> Timeweb Cloud
OK: Как Нейроюрист ищет по миллионам юридических документов с помощью векторного поиска YDB _ Хабр.pdf -> Яндекс
OK: Кибербезопасность финансовой отрасли России в 2026 году_ тенденции защиты и атак _ Хабр.pdf -> Positive Technologies
OK: Космос-2055_ как будет выглядеть космонавтика через 30 лет_ _ Хабр.pdf -> МТС
OK: Поделить огромный проект с автотестами на 50 команд, чтобы QA был счастлив _ Хабр.pdf -> Альфа-Банк
OK: Принципы организационного проектирования _ Хабр.pdf -> OTUS
OK: Хлеб на закваске как управляемый процесс _ Хабр.pdf -> ЮMoney
OK: Что случилось с CGI, и как FastCGI спас веб от катастрофы_ _ Хабр.pdf -> RUVDS.com

Итог: Обработано 18, Ошибок 0

In [96]:
Brak

[]

In [97]:
# Создание DataFrame
df = pd.DataFrame({
'NameCompany': [],
'Description': [],
'Raiting': [],
'DataPublish': [],
'Activity': [],
'TextArticle': []
})

In [98]:
df

Empty DataFrame
Columns: [NameCompany, Description, Raiting, DataPublish, Activity, TextArticle]
Index: []

In [99]:
print(len(NameCompany), len(Description), len(Raiting), len(DataPublish),len(Activity), len(TextArticle) )

18 18 18 18 18 18

In [100]:
NameCompany

['NeyroHub',
 'Сбер',
 'NeyroHub',
 'Selectel',
 'StudyAI',
 'Бастион',
 'RUVDS.com',
 'МТС',
 'AvitoTech',
 'Online patent',
 'Timeweb Cloud',
 'Яндекс',
 'Positive Technologies',
 'МТС',
 'Альфа-Банк',
 'OTUS',
 'ЮMoney',
 'RUVDS.com']

In [101]:
df['NameCompany'] = NameCompany

In [102]:
df['Raiting'] = Raiting

In [103]:
df['DataPublish'] = DataPublish

In [104]:
df['Activity'] = Activity

In [105]:
df['TextArticle'] = TextArticle

In [106]:
df['Description'] = Description

In [107]:
df

,NameCompany,Description,Raiting,DataPublish,Activity,TextArticle
0,NeyroHub,AI-диджей Spotify задумывался как умный помощн...,185.84,17.03.2026,,185.84 Общий рейтинг NeyroHub Подписаться AI-д...
1,Сбер,Продолжаем наши обзоры плагинов к GIgaIDE. Пер...,315.5,16.03.2026,"Технологии, меняющие мир","315.5 Общий рейтинг Сбер Технологии, меняющие ..."
2,NeyroHub,Компания Meta рассматривает масштабные сокраще...,185.84,17.03.2026,,185.84 Общий рейтинг NeyroHub Подписаться Комп...
3,Selectel,"Привет, Хабр! Это Антон Дятлов, инженер по защ...",2497.34,17.03.2026,IT-инфраструктура для бизнеса,4.67 Оценка 2497.34 Общий рейтинг Selectel IT-...
4,StudyAI,Подробное руководство по работе с нейросетью N...,,17.03.2026,,0 Общий рейтинг StudyAI Подписаться Подробное ...
5,Бастион,"В 2024 году мы рассказывали, как развернули ма...",282.06,10.03.2026,На страже цифровых активов,282.06 Общий рейтинг Бастион На страже цифровы...
6,RUVDS.com,Какое железо есть на рынке Стандарт 5 Гбит оче...,3031.1,17.03.2026,VDS/VPS-хостинг. Скидка 15% по коду HABR15,3031.1 Общий рейтинг RUVDS.com VDS/VPS-хостинг...
7,МТС,Источник Apple неожиданно выкатилa MacBook Neo...,1809.66,16.03.2026,Про жизнь и развитие в IT,1809.66 Общий рейтинг МТС Про жизнь и развитие...
8,AvitoTech,"Привет! Я Ангелина Архипова, тимлид QA в Авито...",460.16,06.03.2026,У нас живут ваши объявления,4.39 Оценка 460.16 Общий рейтинг AvitoTech У н...
9,Online patent,Реклама первой веб-камеры gregyku 2 часа назад...,312.98,17.03.2026,Ваш личный патентный офис,312.98 Общий рейтинг Online patent Ваш личный ...
10,Timeweb Cloud,"Привет, Хабр! В одной из прошлых своих статей,...",2148.86,17.03.2026,То самое облако,2148.86 Общий рейтинг Timeweb Cloud То самое о...
11,Яндекс,"Привет, Хабр! Меня зовут Александр Зевайкин, и...",517.02,11.03.2026,Как мы делаем Яндекс,517.02 Общий рейтинг Яндекс Как мы делаем Янде...
12,Positive Technologies,Финансовая отрасль России выступает фундаменто...,451.45,11.03.2026,,4.21 Оценка 451.45 Общий рейтинг Positive Tech...
13,МТС,Утро 17 марта 2055 года. На высоте четырехсот ...,1809.66,17.03.2026,Про жизнь и развитие в IT,1809.66 Общий рейтинг МТС Про жизнь и развитие...
14,Альфа-Банк,"Меня зовут Павел Коростин, я техлид тестирован...",373.67,06.03.2026,Лучший мобильный банк по версии Markswebb,373.67 Общий рейтинг Альфа-Банк Лучший мобильн...
15,OTUS,"«А вы, друзья, как ни садитесь, всё в музыкант...",751.28,17.03.2026,"Развиваем технологии, обучая их создателей",751.28 Общий рейтинг OTUS Развиваем технологии...
16,ЮMoney,"Привет, Хабр! Меня зовут Екатерина, и в ЮMoney...",86.57,17.03.2026,Всё о разработке сервисов онлайн-платежей,4.84 Оценка 86.57 Общий рейтинг ЮMoney Всё о р...
17,RUVDS.com,В девяностых CGI сделал интернет интерактивным...,3131.1,17.03.2026,VDS/VPS-хостинг. Скидка 15% по коду HABR15,3131.1 Общий рейтинг RUVDS.com VDS/VPS-хостинг...

In [108]:
import pandas
df.to_csv(r"dataset.csv")

In [109]:
df2 = pd.read_csv(r"dataset.csv")
df2.head()

,Unnamed: 0,NameCompany,Description,Raiting,DataPublish,Activity,TextArticle
0,0,NeyroHub,AI-диджей Spotify задумывался как умный помощн...,185.84,17.03.2026,NaN,185.84 Общий рейтинг NeyroHub Подписаться AI-д...
1,1,Сбер,Продолжаем наши обзоры плагинов к GIgaIDE. Пер...,315.50,16.03.2026,"Технологии, меняющие мир","315.5 Общий рейтинг Сбер Технологии, меняющие ..."
2,2,NeyroHub,Компания Meta рассматривает масштабные сокраще...,185.84,17.03.2026,NaN,185.84 Общий рейтинг NeyroHub Подписаться Комп...
3,3,Selectel,"Привет, Хабр! Это Антон Дятлов, инженер по защ...",2497.34,17.03.2026,IT-инфраструктура для бизнеса,4.67 Оценка 2497.34 Общий рейтинг Selectel IT-...
4,4,StudyAI,Подробное руководство по работе с нейросетью N...,NaN,17.03.2026,NaN,0 Общий рейтинг StudyAI Подписаться Подробное ...